version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    command: mongod --auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: soravideo
    restart: 'always'

  redis:
    image: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=moment
    command: redis-server --requirepass moment
    volumes:
      - redis-data:/data
    restart: always

  minio:
    image: minio/minio
    volumes:
      - data:/data
      - config:/root/.minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: moment
      MINIO_ROOT_PASSWORD: moment666
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mongodata:
  config:
  redis-data:
  data:
